import torch
# data_list = get_data_objects(ANNOTATION_FOLDER,IMAGES_FOLDER,QUESTIONS_FOLDER)
# dataframe = create_dataframe(data_list)
# logger.info("Starting annotations")
# # execute_full_set_annotation(DATA_JSON,ANNOTATED_IMAGES_FOLDER)
# id_list = list(dataframe["image_id"])
# annotated_image_path= [str(ANNOTATED_IMAGES_FOLDER / f"{id}.png") for id in id_list]

# # print([type(Path(image).name) for image in id_list[:25]])
# # print(annotated_image_path[:25])

# # print(len(id_list))
# output=get_multiple_embeddings(annotated_image_path[:25])
# print(type(output['5']))
labels = torch.tensor(0)
unsqueezed = labels.unsqueeze(0)
print(labels)
print(unsqueezed)
labels = torch.tensor(1)
unsqueezed = labels.unsqueeze(0)
print(labels)
print(unsqueezed)
labels = torch.tensor(2)
unsqueezed = labels.unsqueeze(0)
print(labels)
print(unsqueezed)